### ISSUE TITLE
Yusra's Peer Review

### ISSUE THREAD

**Issue by ysyed1** [sbroderick1/project#3]
Love the idea & how you get to be creative, incorporating your personal style into website!

Tech suggestions:
- fieldset should be inside of form
- Put image size dimensions in CSS

Content suggestions:
- More about top influencers, maybe embedding their social medias into your page
- Interactive header, dropdown menu, logo
- Spelling mistakes

**Comment by sbroderick1** [comment]
Thanks so much for all your suggestions! I will be fixing and implementing everything you said in your comment!
