### ISSUE TITLE
Gabrielle's Suggestions

### ISSUE THREAD

**Issue by gabriellemiller** [sbroderick1/project#4]
Can't wait to see the end result of this project!

Tech suggestions:
- In your About Me page: I suggest adding another page about your portfolio so people can navigate through it freely rather than just adding an img
- Embed YouTube videos and links to websites when you add content to you Current Events page

Content suggestions:
- As you embed CSS make sure to stay consistent with fonts and colors throughout all of your webpages
- I love your header that you made on Canva! I suggest following that color scheme to match the content of you web page
- Maybe add your style icons and links to things you enjoy reading/following?

**Comment by sbroderick1** [comment]
Thank you so much for your review! I like your idea about making a separate page for a portfolio I will definitely use that. And i was planning to use some videos on the current events page I just haven't done the content for that page yet. 
Thank you for all the CSS tips I will make sure I include those as I go
